/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-bright": "#fef9f1",
        "on-secondary-fixed": "#1c1b1b",
        "inverse-surface": "#32302b",
        "on-secondary-fixed-variant": "#474746",
        "on-error": "#ffffff",
        "on-tertiary-container": "#503f00",
        "surface-tint": "#735b24",
        "error-container": "#ffdad6",
        "on-background": "#1d1c17",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed": "#241a00",
        tertiary: "#735c00",
        "inverse-on-surface": "#f5f0e8",
        "surface-container-low": "#f8f3eb",
        "surface-container": "#f2ede5",
        "secondary-container": "#e2dfde",
        "surface-dim": "#ded9d2",
        "on-surface-variant": "#4d463a",
        "surface-container-lowest": "#ffffff",
        secondary: "#5f5e5e",
        "on-tertiary": "#ffffff",
        "primary-container": "#c8a96a",
        "on-primary-fixed-variant": "#5a430e",
        "on-secondary-container": "#636262",
        background: "#fef9f1",
        "surface-variant": "#e7e2da",
        "tertiary-fixed-dim": "#e9c349",
        "on-primary-fixed": "#261a00",
        "secondary-fixed": "#e5e2e1",
        "secondary-fixed-dim": "#c8c6c5",
        "on-primary": "#ffffff",
        surface: "#fef9f1",
        error: "#ba1a1a",
        primary: "#735b24",
        outline: "#7f7668",
        "tertiary-container": "#cea931",
        "outline-variant": "#d0c5b5",
        "tertiary-fixed": "#ffe088",
        "on-primary-container": "#533d07",
        "primary-fixed": "#ffdf9f",
        "primary-fixed-dim": "#e3c281",
        "surface-container-high": "#ece8e0",
        "on-surface": "#1d1c17",
        "on-error-container": "#93000a",
        "on-tertiary-fixed-variant": "#574500",
        "inverse-primary": "#e3c281",
        "surface-container-highest": "#e7e2da",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "margin-mobile": "20px",
        unit: "8px",
        "margin-desktop": "64px",
        gutter: "24px",
        "section-padding": "80px",
        "container-max": "1200px",
      },
      fontFamily: {
        "display-md": ["Playfair Display", "serif"],
        "display-lg": ["Playfair Display", "serif"],
        "headline-lg-mobile": ["Playfair Display", "serif"],
        "label-sm": ["Cairo", "sans-serif"],
        "body-lg": ["Cairo", "sans-serif"],
        "headline-lg": ["Playfair Display", "serif"],
        "label-md": ["Cairo", "sans-serif"],
        "body-md": ["Cairo", "sans-serif"],
      },
      fontSize: {
        "display-md": ["36px", { lineHeight: "1.2", fontWeight: "600" }],
        "display-lg": [
          "48px",
          { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "headline-lg-mobile": [
          "24px",
          { lineHeight: "1.3", fontWeight: "600" },
        ],
        "label-sm": ["12px", { lineHeight: "1.2", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-lg": ["28px", { lineHeight: "1.3", fontWeight: "600" }],
        "label-md": [
          "14px",
          { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "600" },
        ],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
      },
      maxWidth: {
        "container-max": "1200px",
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
};
